const SET_PROFILE = "SET_PROFILE";
const SET_AUTH = "SET_AUTH";
const ADD_PROFILE_LOADING = "ADD_PROFILE_LOADING";
const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
const ADD_PROFILE_ERROR = "ADD_PROFILE_ERROR";

export default {
  SET_PROFILE,
  SET_AUTH,
  ADD_PROFILE_LOADING,
  ADD_PROFILE_SUCCESS,
  ADD_PROFILE_ERROR,
};
