export const SET_PROFILE = 'SET_PROFILE';
export const SET_AUTH = 'SET_AUTH';
export const ADD_PROFILE_LOADING = 'ADD_PROFILE_LOADING';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_ERROR = 'ADD_PROFILE_ERROR';

