export const SET_VERIFICATION_UNASSIGNED = "SET_VERIFICATION_UNASSIGNED";
export const SET_VERIFICATION_UNASSIGNED_SEARCHED =
  "SET_VERIFICATION_UNASSIGNED_SEARCHED";

export const SET_VERIFICATION_UNFINISHED = "SET_VERIFICATION_UNFINISHED";
export const SET_VERIFICATION_UNFINISHED_SEARCHED =
  "SET_VERIFICATION_UNFINISHED_SEARCHED";
export const SET_VERIFICATION_OTHERS_UNFINISHED =
  "SET_VERIFICATION_OTHERS_UNFINISHED";
export const SET_VERIFICATION_OTHERS_UNFINISHED_SEARCHED =
  "SET_VERIFICATION_OTHERS_UNFINISHED_SEARCHED";

const baseUrl = "https://hrlicensurebe.dev.k8s.sandboxaddis.com/api";

export default {
  SET_VERIFICATION_UNASSIGNED,
  SET_VERIFICATION_UNASSIGNED_SEARCHED,

  SET_VERIFICATION_UNFINISHED,
  SET_VERIFICATION_UNFINISHED_SEARCHED,
  SET_VERIFICATION_OTHERS_UNFINISHED,
  SET_VERIFICATION_OTHERS_UNFINISHED_SEARCHED,
};
