export const SET_VERIFICATION_UNASSIGNED = "SET_VERIFICATION_UNASSIGNED";
export const SET_VERIFICATION_UNASSIGNED_SEARCHED =
  "SET_VERIFICATION_UNASSIGNED_SEARCHED";

export const SET_VERIFICATION_UNFINISHED = "SET_VERIFICATION_UNFINISHED";
export const SET_VERIFICATION_UNFINISHED_SEARCHED =
  "SET_VERIFICATION_UNFINISHED_SEARCHED";
export const SET_VERIFICATION_OTHERS_UNFINISHED =
  "SET_VERIFICATION_OTHERS_UNFINISHED";
export const SET_VERIFICATION_OTHERS_UNFINISHED_SEARCHED =
  "SET_VERIFICATION_OTHERS_UNFINISHED_SEARCHED";

export const SET_VERIFICATION_ASSIGNED_TO_YOU =
  "SET_VERIFICATION_ASSIGNED_TO_YOU";
export const SET_VERIFICATION_ASSIGNED_TO_YOU_SEARCHED =
  "SET_VERIFICATION_ASSIGNED_TO_YOU_SEARCHED";
export const SET_VERIFICATION_ASSIGNED_TO_OTHERS =
  "SET_VERIFICATION_ASSIGNED_TO_OTHERS";
export const SET_VERIFICATION_ASSIGNED_TO_OTHERS_SEARCHED =
  "SET_VERIFICATION_ASSIGNED_TO_OTHERS_SEARCHED";

export const SET_VERIFICATION_APPROVED = "SET_VERIFICATION_APPROVED";
export const SET_VERIFICATION_APPROVED_SEARCHED =
  "SET_VERIFICATION_APPROVED_SEARCHED";
export const SET_VERIFICATION_ALL_APPROVED = "SET_VERIFICATION_ALL_APPROVED";
export const SET_VERIFICATION_ALL_APPROVED_SEARCHED =
  "SET_VERIFICATION_ALL_APPROVED_SEARCHED";

export const SET_VERIFICATION_DECLINED = "SET_VERIFICATION_DECLINED";
export const SET_VERIFICATION_DECLINED_SEARCHED = "SET_VERIFICATION_DECLINED_SEARCHED";
export const SET_VERIFICATION_ALL_DECLINED = "SET_VERIFICATION_ALL_DECLINED";
export const SET_VERIFICATION_ALL_DECLINED_SEARCHED =
  "SET_VERIFICATION_ALL_DECLINED_SEARCHED";

export const SET_VERIFICATION_UNDER_SUPERVISION =
  "SET_VERIFICATION_UNDER_SUPERVISION";
export const SET_VERIFICATION_UNDER_SUPERVISION_SEARCHED =
  "SET_VERIFICATION_UNDER_SUPERVISION_SEARCHED";
export const SET_VERIFICATION_OTHERS_UNDER_SUPERVISION =
  "SET_VERIFICATION_OTHERS_UNDER_SUPERVISION";
export const SET_VERIFICATION_OTHERS_UNDER_SUPERVISION_SEARCHED =
  "SET_VERIFICATION_OTHERS_UNDER_SUPERVISION_SEARCHED";


const baseUrl = "https://hrlicensurebe.dev.k8s.sandboxaddis.com/api";

export default {
  SET_VERIFICATION_UNASSIGNED,
  SET_VERIFICATION_UNASSIGNED_SEARCHED,

  SET_VERIFICATION_UNFINISHED,
  SET_VERIFICATION_UNFINISHED_SEARCHED,
  SET_VERIFICATION_OTHERS_UNFINISHED,
  SET_VERIFICATION_OTHERS_UNFINISHED_SEARCHED,

  SET_VERIFICATION_ASSIGNED_TO_YOU,
  SET_VERIFICATION_ASSIGNED_TO_YOU_SEARCHED,
  SET_VERIFICATION_ASSIGNED_TO_OTHERS,
  SET_VERIFICATION_ASSIGNED_TO_OTHERS_SEARCHED,

  SET_VERIFICATION_APPROVED,
  SET_VERIFICATION_APPROVED_SEARCHED,
  SET_VERIFICATION_ALL_APPROVED,
  SET_VERIFICATION_ALL_APPROVED_SEARCHED,

  SET_VERIFICATION_DECLINED,
  SET_VERIFICATION_DECLINED_SEARCHED,
  SET_VERIFICATION_ALL_DECLINED,
  SET_VERIFICATION_ALL_DECLINED_SEARCHED,

  SET_VERIFICATION_UNDER_SUPERVISION,
  SET_VERIFICATION_UNDER_SUPERVISION_SEARCHED,
  SET_VERIFICATION_OTHERS_UNDER_SUPERVISION,
  SET_VERIFICATION_OTHERS_UNDER_SUPERVISION_SEARCHED,
};
