export default {
  state: {
    applicantId: "",
    residenceWoredaId: "",
    applicantTitle: "",
    whomGoodStandingFor: "",
    licenseIssuedDate: "",
    whoIssued: "",
    licenseRegistrationNumber: "",
    applicantPositionId: "",
    professionalTypeId: "",
    licenseCopy: "",
    serviceFee: "",
    goodStandingLetter: "",
    buttons: [],
    applicationId: 0,
    documentSpec: [],
    draft: "",
    declinedFields: [],
    acceptedFields: [],
    remark: "",
  },
};
