export default {
    state: {
        applicantId: "",
        residenceWoredaId: "",
        expertLevelId: "",
        applicantTitle: "",
        whomGoodStandingFor: "",
        licenseIssuedDate: "",
        whoIssued: "",
        licenseRegistrationNumber: "",
        applicantPositionId: "",
        professionalTypeId: "",
        otherProfessionalType: "",
        buttons: [],
        applicationId: 0,
        documentSpec: [],
        draft: "",
        declinedFields: [],
        acceptedFields: [],
        remark: "",
        licenseCopy: "",
        goodStandingLetter: "",
        serviceFee: "",
    },
};