export default {
  getLicense: (state) => state.license,
  getPassport: (state) => state.passport,
  getHealthExamCert: (state) => state.healthExamCert,
  getEnglishLanguage: (state) => state.englishLanguage,
  getProfessionalDocuments: (state) => state.professionalDocuments,
  getHerqa: (state) => state.herqa,
  getSupportLetter: (state) => state.supportLetter,
  getCoc: (state) => state.coc,
  getEducationalDocuments: (state) => state.educationalDocuments,
  getWorkExperience: (state) => state.workExperience,
  getServiceFee: (state) => state.serviceFee,
  getLetterfromOrg: (state) => state.letterfromOrg,
  getRenewedLicense: (state) => state.renewedLicense,
  getPayroll: (state) => state.payroll,
  getProfessionalLicense: (state) => state.professionalLicense,
  getButtons: (state) => state.buttons,
  getApplicationId: (state) => state.applicationId,
  getDocumentSpec: (state) => state.documentSpec,
  getDraft: (state) => state.draft,
  getRemark: (state) => state.remark,
  getDeclinedFields: (state) => state.declinedFields,
  getAcceptedFields: (state) => state.acceptedFields,
};
