export default {
  getLicense: (state) => state.license,
  getPhoto: (state) => state.photo,
  getPassport: (state) => state.passport,
  getHealthExamCert: (state) => state.healthExamCert,
  getEnglishLanguage: (state) => state.englishLanguage,
  getProfessionalDocuments: (state) => state.professionalDocuments,
  getHerqa: (state) => state.herqa,
  getSupportLetter: (state) => state.supportLetter,
  getCoc: (state) => state.coc,
  getEducationalDocuments: (state) => state.educationalDocuments,
  getWorkExperience: (state) => state.workExperience,
  getServiceFee: (state) => state.serviceFee,
  getButtons: (state) => state.buttons,
  getApplicationId: (state) => state.applicationId,
  getDocumentSpec: (state) => state.documentSpec,
  getDraft: (state) => state.draft,
};
