const SET_LICENSE = "SET_LICENSE";
const ADD_PROFILE_LOADING = "ADD_PROFILE_LOADING";
const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
const ADD_PROFILE_ERROR = "ADD_PROFILE_ERROR";
export default {
  SET_LICENSE,
  ADD_PROFILE_LOADING,
  ADD_PROFILE_SUCCESS,
  ADD_PROFILE_ERROR,
};
