export default {
  state: {
    applicantId: "",
    applicantTypeId: "",
    education: {
      departmentId: "",
      institutionId: "",
    },
    photo: "",
    passport: "",
    healthExamCert: "",
    englishLanguage: "",
    professionalDocuments: [],
    herqa: "",
    supportLetter: "",
    coc: "",
    educationalDocuments: [],
    workExperience: "",
    serviceFee: "",
    letterfromOrg: "",
    renewedLicense: "",
    professionalLicense: "",
    buttons: [],
    applicationId: 0,
    documentSpec: [],
    draft: "",
  },
};
