export default {
  state: {
    applicantId: "",
    applicantTypeId: "",
    education: {
      departmentId: "",
      institutionId: "",
    },
    residenceWoredaId: "",
    professionalTypeId: "",
    occupationTypeId: "",
    nativeLanguageId: "",
    paymentSlip: null,
    passport: "",
    healthExamCert: "",
    englishLanguage: "",
    professionalDocuments: [],
    herqa: "",
    supportLetter: "",
    coc: "",
    educationalDocuments: [],
    workExperience: "",
    serviceFee: "",
    letterfromOrg: "",
    payroll: "",
    renewedLicense: "",
    professionalLicense: "",
    degree: "",
    transcript: "",
    diploma: "",
    buttons: [],
    applicationId: 0,
    documentSpec: [],
    draft: "",
    declinedFields: [],
    acceptedFields: [],
    remark: "",
  },
};
