export const SET_RENEWAL_UNASSIGNED = "SET_RENEWAL_UNASSIGNED";
export const SET_RENEWAL_UNASSIGNED_SEARCHED =
  "SET_RENEWAL_UNASSIGNED_SEARCHED";

export const SET_RENEWAL_UNFINISHED = "SET_RENEWAL_UNFINISHED";
export const SET_RENEWAL_UNFINISHED_SEARCHED =
  "SET_RENEWAL_UNFINISHED_SEARCHED";
export const SET_RENEWAL_OTHERS_UNFINISHED = "SET_RENEWAL_OTHERS_UNFINISHED";
export const SET_RENEWAL_OTHERS_UNFINISHED_SEARCHED =
  "SET_RENEWAL_OTHERS_UNFINISHED_SEARCHED";

export const SET_RENEWAL_ASSIGNED_TO_YOU =
  "SET_RENEWAL_ASSIGNED_TO_YOU";
export const SET_RENEWAL_ASSIGNED_TO_YOU_SEARCHED =
  "SET_RENEWAL_ASSIGNED_TO_YOU_SEARCHED";
export const SET_RENEWAL_ASSIGNED_TO_OTHERS =
  "SET_RENEWAL_ASSIGNED_TO_OTHERS";
export const SET_RENEWAL_ASSIGNED_TO_OTHERS_SEARCHED =
  "SET_RENEWAL_ASSIGNED_TO_OTHERS_SEARCHED";

const baseUrl = "https://hrlicensurebe.dev.k8s.sandboxaddis.com/api";

export default {
  SET_RENEWAL_UNASSIGNED,
  SET_RENEWAL_UNASSIGNED_SEARCHED,

  SET_RENEWAL_UNFINISHED,
  SET_RENEWAL_UNFINISHED_SEARCHED,
  SET_RENEWAL_OTHERS_UNFINISHED,
  SET_RENEWAL_OTHERS_UNFINISHED_SEARCHED,

  SET_RENEWAL_ASSIGNED_TO_YOU,
  SET_RENEWAL_ASSIGNED_TO_YOU_SEARCHED,
  SET_RENEWAL_ASSIGNED_TO_OTHERS,
  SET_RENEWAL_ASSIGNED_TO_OTHERS_SEARCHED,
};
