export const SET_PROFILE = "SET_PROFILE";
export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_CONTACT = "SET_CONTACT";
export const ADD_PROFILE_LOADING = "ADD_PROFILE_LOADING";
export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
export const ADD_PROFILE_ERROR = "ADD_PROFILE_ERROR";

export default {
  SET_PROFILE,
  SET_PERSONAL_INFO,
  SET_ADDRESS,
  SET_CONTACT,
  ADD_PROFILE_LOADING,
  ADD_PROFILE_SUCCESS,
  ADD_PROFILE_ERROR
};
