export const SET_LICENSE = "SET_LICENSE";
export const ADD_PROFILE_LOADING = "ADD_PROFILE_LOADING";
export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
export const ADD_PROFILE_ERROR = "ADD_PROFILE_ERROR";
export const SET_ACTIVE_STATE = "SET_ACTIVE_STATE";
export const SET_PHOTO = "SET_PHOTO";
export const SET_PASSPORT = "SET_PASSPORT";
export const SET_HEALTH_EXAM_CERT = "SET_HEALTH_EXAM_CERT";
export const SET_DOCS = "SET_DOCS";

export default {
    SET_LICENSE,
    ADD_PROFILE_LOADING,
    ADD_PROFILE_SUCCESS,
    ADD_PROFILE_ERROR,
    SET_ACTIVE_STATE,
    SET_PHOTO,
    SET_PASSPORT,
    SET_HEALTH_EXAM_CERT,
    SET_DOCS
  };
  