export const SET_NEW_LICENSE_UNASSIGNED = "SET_NEW_LICENSE_UNASSIGNED";
export const SET_NEW_LICENSE_UNASSIGNED_SEARCHED =
  "SET_NEW_LICENSE_UNASSIGNED_SEARCHED";

export const SET_NEW_LICENSE_UNFINISHED = "SET_NEW_LICENSE_UNFINISHED";
export const SET_NEW_LICENSE_UNFINISHED_SEARCHED =
  "SET_NEW_LICENSE_UNFINISHED_SEARCHED";
export const SET_NEW_LICENSE_OTHERS_UNFINISHED =
  "SET_NEW_LICENSE_OTHERS_UNFINISHED";
export const SET_NEW_LICENSE_OTHERS_UNFINISHED_SEARCHED =
  "SET_NEW_LICENSE_OTHERS_UNFINISHED_SEARCHED";

export const SET_NEW_LICENSE_ASSIGNED_TO_YOU =
  "SET_NEW_LICENSE_ASSIGNED_TO_YOU";
export const SET_NEW_LICENSE_ASSIGNED_TO_YOU_SEARCHED =
  "SET_NEW_LICENSE_ASSIGNED_TO_YOU_SEARCHED";
export const SET_NEW_LICENSE_ASSIGNED_TO_OTHERS =
  "SET_NEW_LICENSE_ASSIGNED_TO_OTHERS";
export const SET_NEW_LICENSE_ASSIGNED_TO_OTHERS_SEARCHED =
  "SET_NEW_LICENSE_ASSIGNED_TO_OTHERS_SEARCHED";

export default {
  SET_NEW_LICENSE_UNASSIGNED,
  SET_NEW_LICENSE_UNASSIGNED_SEARCHED,

  SET_NEW_LICENSE_UNFINISHED,
  SET_NEW_LICENSE_UNFINISHED_SEARCHED,
  SET_NEW_LICENSE_OTHERS_UNFINISHED,
  SET_NEW_LICENSE_OTHERS_UNFINISHED_SEARCHED,

  SET_NEW_LICENSE_ASSIGNED_TO_YOU,
  SET_NEW_LICENSE_ASSIGNED_TO_YOU_SEARCHED,
  SET_NEW_LICENSE_ASSIGNED_TO_OTHERS,
  SET_NEW_LICENSE_ASSIGNED_TO_OTHERS_SEARCHED,
};
