export const SET_NEW_LICENSE_UNASSIGNED = "SET_NEW_LICENSE_UNASSIGNED";
export const SET_NEW_LICENSE_UNASSIGNED_SEARCHED =
  "SET_NEW_LICENSE_UNASSIGNED_SEARCHED";

export const SET_NEW_LICENSE_UNFINISHED = "SET_NEW_LICENSE_UNFINISHED";
export const SET_NEW_LICENSE_UNFINISHED_SEARCHED =
  "SET_NEW_LICENSE_UNFINISHED_SEARCHED";
export const SET_NEW_LICENSE_OTHERS_UNFINISHED =
  "SET_NEW_LICENSE_OTHERS_UNFINISHED";
export const SET_NEW_LICENSE_OTHERS_UNFINISHED_SEARCHED =
  "SET_NEW_LICENSE_OTHERS_UNFINISHED_SEARCHED";

export const SET_NEW_LICENSE_ASSIGNED_TO_YOU =
  "SET_NEW_LICENSE_ASSIGNED_TO_YOU";
export const SET_NEW_LICENSE_ASSIGNED_TO_YOU_SEARCHED =
  "SET_NEW_LICENSE_ASSIGNED_TO_YOU_SEARCHED";
export const SET_NEW_LICENSE_ASSIGNED_TO_OTHERS =
  "SET_NEW_LICENSE_ASSIGNED_TO_OTHERS";
export const SET_NEW_LICENSE_ASSIGNED_TO_OTHERS_SEARCHED =
  "SET_NEW_LICENSE_ASSIGNED_TO_OTHERS_SEARCHED";

export const SET_NEW_LICENSE_APPROVED =
  "SET_NEW_LICENSE_APPROVED";
export const SET_NEW_LICENSE_APPROVED_SEARCHED =
  "SET_NEW_LICENSE_APPROVED_SEARCHED";
export const SET_NEW_LICENSE_ALL_APPROVED =
  "SET_NEW_LICENSE_ALL_APPROVED";
export const SET_NEW_LICENSE_ALL_APPROVED_SEARCHED =
  "SET_NEW_LICENSE_ALL_APPROVED_SEARCHED";

export const SET_NEW_LICENSE_DECLINED =
  "SET_NEW_LICENSE_DECLINED";
export const SET_NEW_LICENSE_DECLINED_SEARCHED =
  "SET_NEW_LICENSE_DECLINED_SEARCHED";
export const SET_NEW_LICENSE_ALL_DECLINED =
  "SET_NEW_LICENSE_ALL_DECLINED";
export const SET_NEW_LICENSE_ALL_DECLINED_SEARCHED =
  "SET_NEW_LICENSE_ALL_DECLINED_SEARCHED";

export const SET_NEW_LICENSE_UNDER_SUPERVISION =
  "SET_NEW_LICENSE_UNDER_SUPERVISION";
export const SET_NEW_LICENSE_UNDER_SUPERVISION_SEARCHED =
  "SET_NEW_LICENSE_UNDER_SUPERVISION_SEARCHED";
export const SET_NEW_LICENSE_OTHERS_UNDER_SUPERVISION =
  "SET_NEW_LICENSE_OTHERS_UNDER_SUPERVISION";
export const SET_NEW_LICENSE_OTHERS_UNDER_SUPERVISION_SEARCHED =
  "SET_NEW_LICENSE_OTHERS_UNDER_SUPERVISION_SEARCHED";
export default {
  SET_NEW_LICENSE_UNASSIGNED,
  SET_NEW_LICENSE_UNASSIGNED_SEARCHED,

  SET_NEW_LICENSE_UNFINISHED,
  SET_NEW_LICENSE_UNFINISHED_SEARCHED,
  SET_NEW_LICENSE_OTHERS_UNFINISHED,
  SET_NEW_LICENSE_OTHERS_UNFINISHED_SEARCHED,

  SET_NEW_LICENSE_ASSIGNED_TO_YOU,
  SET_NEW_LICENSE_ASSIGNED_TO_YOU_SEARCHED,
  SET_NEW_LICENSE_ASSIGNED_TO_OTHERS,
  SET_NEW_LICENSE_ASSIGNED_TO_OTHERS_SEARCHED,

  SET_NEW_LICENSE_APPROVED,
  SET_NEW_LICENSE_APPROVED_SEARCHED,
  SET_NEW_LICENSE_ALL_APPROVED,
  SET_NEW_LICENSE_ALL_APPROVED_SEARCHED,

  SET_NEW_LICENSE_DECLINED,
  SET_NEW_LICENSE_DECLINED_SEARCHED,
  SET_NEW_LICENSE_ALL_DECLINED,
  SET_NEW_LICENSE_ALL_DECLINED_SEARCHED,

  SET_NEW_LICENSE_UNDER_SUPERVISION,
  SET_NEW_LICENSE_UNDER_SUPERVISION_SEARCHED,
  SET_NEW_LICENSE_OTHERS_UNDER_SUPERVISION,
  SET_NEW_LICENSE_OTHERS_UNDER_SUPERVISION_SEARCHED

};
