export const SET_GOOD_STANDING_UNASSIGNED = "SET_GOOD_STANDING_UNASSIGNED";
export const SET_GOOD_STANDING_UNASSIGNED_SEARCHED =
  "SET_GOOD_STANDING_UNASSIGNED_SEARCHED";

const baseUrl = "https://hrlicensurebe.dev.k8s.sandboxaddis.com/api";

export default {
    SET_GOOD_STANDING_UNASSIGNED,
    SET_GOOD_STANDING_UNASSIGNED_SEARCHED,
};
