export const SET_LICENSE = "SET_LICENSE";
export const SET_RENEWAL_HEALTH_EXAM_CERT = "SET_RENEWAL_HEALTH_EXAM_CERT";
export const SET_RENEWAL_LETTER = "SET_RENEWAL_LETTER";
export const SET_RENEWAL_WORK_EXPERIENCE = "SET_RENEWAL_WORK_EXPERIENCE";
export const SET_RENEWAL_SERVICE_FEE = "SET_RENEWAL_SERVICE_FEE";
export const SET_RENEWAL_CPD = "SET_RENEWAL_CPD";
export const SET_PREVIOUS_LICEENSE = "SET_PREVIOUS_LICEENSE";
export const SET_BUTTONS = "SET_BUTTONS";
export const SET_APPLICATION_ID = "SET_APPLICATION_ID";
export const SET_DOCUMENT_SPEC = "SET_DOCUMENT_SPEC";
export const SET_DRAFT = "SET_DRAFT";
export const SET_DECLINED_FIELDS = "SET_DECLINED_FIELDS";
export const SET_ACCEPTED_FIELDS = "SET_ACCEPTED_FIELDS";
export const SET_REMARK = "SET_REMARK";

export default {
  SET_LICENSE,
  SET_RENEWAL_HEALTH_EXAM_CERT,
  SET_RENEWAL_LETTER,
  SET_RENEWAL_WORK_EXPERIENCE,
  SET_RENEWAL_SERVICE_FEE,
  SET_RENEWAL_CPD,
  SET_PREVIOUS_LICEENSE,
  SET_BUTTONS,
  SET_APPLICATION_ID,
  SET_DOCUMENT_SPEC,
  SET_DRAFT,
  SET_DECLINED_FIELDS,
  SET_ACCEPTED_FIELDS,
  SET_REMARK,
};
