export const SET_RENEWAL = "SET_RENEWAL";
// export const ADD_PROFILE_LOADING = "ADD_PROFILE_LOADING";
// export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
// export const ADD_PROFILE_ERROR = "ADD_PROFILE_ERROR";
// export const SET_ACTIVE_STATE = "SET_ACTIVE_STATE";
export const SET_RENEWAL_PHOTO = "SET_RENEWAL_PHOTO";
export const SET_RENEWAL_PASSPORT = "SET_RENEWAL_PASSPORT";
export const SET_RENEWAL_HEALTH_EXAM_CERT = "SET_RENEWAL_HEALTH_EXAM_CERT";
export const SET_RENEWAL_SERVICE_FEE = "SET_RENEWAL_SERVICE_FEE";
export const SET_RENEWAL_CPD = "SET_RENEWAL_CPD";
export const SET_RENEWAL_WORK_EXPERIENCE = "SET_RENEWAL_WORK_EXPERIENCE";
export const SET_DOCS = "SET_DOCS";

export default {
  SET_RENEWAL,
  // ADD_PROFILE_LOADING,
  // ADD_PROFILE_SUCCESS,
  // ADD_PROFILE_ERROR,
  // SET_ACTIVE_STATE,
  SET_RENEWAL_PHOTO,
  SET_RENEWAL_PASSPORT,
  SET_RENEWAL_HEALTH_EXAM_CERT,
  SET_RENEWAL_SERVICE_FEE,
  SET_RENEWAL_CPD,
  SET_RENEWAL_WORK_EXPERIENCE,
  SET_DOCS,
};
