export default {
  state: {
    applicantId: "",
    applicantTypeId: "",
    education: {
      departmentId: "",
      institutionId: "",
    },
    residenceWoredaId: "",
    professionalTypeId: "",
    occupationTypeId: "",
    paymentSlip: null,
    healthExamCert: "",
    workExperience: "",
    letterFromHiringInstitution: "",
    professionalDocuments: [],
    serviceFee: "",
    previosLicense: "",
    cpd: "",
    payroll: "",
    buttons: [],
    applicationId: 0,
    documentSpec: [],
    draft: "",
    declinedFields: [],
    acceptedFields: [],
    remark: "",
  },
};
