export default {
  state: {
    applicantId: "",
    applicantTypeId: "",
    education: {
      departmentId: "",
      institutionId: "",
    },
    residenceWoredaId: "",
    professionalTypeId: "",
    occupationTypeId: "",
    expertLevelId: "",
    paymentSlip: null,
    healthExamCert: "",
    workExperience: "",
    letterFromHiringInstitution: "",
    professionalDocuments: [],
    certificate: "",
    diploma: "",
    transcript: "",
    serviceFee: "",
    previosLicense: "",
    cpd: "",
    payroll: "",

    passport: "",
    englishLanguage: "",
    herqa: "",
    letterfromOrg: "",
    professionalLicense: "",
    renewedLicense: "",
    coc: "",
    degree: "",
    educationalDocuments: [],
    eduEighthGrade: "",
    eduTenthGrade: "",
    eduTwelvethGrade: "",
    eduTranscript1: "",
    eduTranscript2: "",
    supportLetter: "",
    proCertificate: "",
    proDiploma: "",
    proTranscript: "",

    buttons: [],
    applicationId: 0,
    documentSpec: [],
    draft: "",
    declinedFields: [],
    acceptedFields: [],
    remark: "",
  },
};
